name: Flutter CI & Deploy

on:
  pull_request:
    branches:
      - main
      - dev

  push:
    branches:
      - main
      - dev

jobs:
  flutter-ci:
    name: Lint, Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔍 Analyze
        run: flutter analyze

      - name: 🧹 Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: 🧪 Run tests
        run: flutter test --no-pub

  deploy:
    name: Deploy to Firebase Hosting
    needs: flutter-ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: 🧱 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: 🧰 Build Flutter Web
        run: flutter build web --release

      - name: 🔥 Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: ${{ github.ref_name == 'main' && 'live' || 'dev' }}
          projectId: ${{ github.ref_name == 'main' && 'pokemon-app-temp' }}
